env: development
project_name: 'surgicare-api-gateway'
namespace: 'dev-surgicare'
fqdn: '{{ project_name }}.dev.surgicare.in'
tag: '{{ prefix }}-{{ build_number }}'
context: nipe-eks-dev
env_during_build: False
min_replicas: 2
max_replicas: 3
aws_profile: nipe
configmap:
  ENV: dev
  DEPENDENCIES: mysql,redis
  DATABASE_HOST: surgicare-cms-dev.cemnwxhq1soi.ap-south-1.rds.amazonaws.com
  DATABASE_PORT: 3306
  DATABASE_NAME: surgicare_lms
  REDIS_ADDRS: nipe-redis-dev.gyk1fw.ng.0001.aps1.cache.amazonaws.com:6379
  GRPC_PORT: 8000